export const products = [
    {
        id: 1,
        title: "Samsung s21 ultra",
        description: "black in color",
        price: "100500",
        img: "https://images.samsung.com/is/image/samsung/p6pim/my/galaxy-s21/gallery/my-galaxy-s21-ultra-5g-g988-sm-g998bzkgxme-368319296?$720_576_PNG$",
        quantity: 1,
    },
    {
        id: 2,
        title: "HP 27f monitor",
        description: "HP 27f 27-inch full HD (1920 x 1080 @ 60 Hz)",
        price: "10300",
        img: "https://www.startech.com.bd/image/cache/catalog/monitor/hp-monitor/27f/hp-27f-1-500x500.jpg",
        quantity: 1,
    },
    {
        id: 3,
        title: "Redmi 9",
        description: "black in color",
        price: "30500",
        img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 4,
        title: "One plus 8",
        description: "Silver white color. 6/128GB variant",
        price: "90500",
        img: "https://www.mobiledokan.co/wp-content/uploads/2019/12/OnePlus-8-Gradient.jpg",
        quantity: 1,
    },
    {
        id: 5,
        title: "MSI GF63",
        description: "Powerful gaming laptop in the world",
        price: "2500",
        img: "https://www.startech.com.bd/image/cache/catalog/laptop/msi/gf63-thin-10scsr/gf63-thin-10scsr-1-500x500.jpg",
        quantity: 1,
    },
    {
        id: 6,
        title: "One Plus 9",
        description: "6GB, 128GB of internal Storage with 50MP camera",
        price: "35000",
        img: "https://www.mobiledokan.co/wp-content/uploads/2020/10/OnePlus-9-Winter-Mist.jpg",
        quantity: 1,
    },
    {
        id: 7,
        title: "Vivobook S531FL",
        description: "Brand Asus, 8GB , 256GB SSD, windows 10 Home",
        price: "72000",
        img: "https://www.startech.com.bd/image/cache/catalog/laptop/asus/s531fl/s531fl-500x500.jpg",
        quantity: 1,
    },
    {
        id: 8,
        title: "Iphone 12",
        description: "6GB, 128GB of internal Storage",
        price: "90500",
        img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 9,
        title: "Canon 4000D",
        description: "AI Focus (Switches between One-Shot AF and AI SERVO AF automatically)",
        price: "25000",
        img: "https://www.startech.com.bd/image/cache/catalog/camera/dslr-camera/canon/4000d/4000d-1-500x500.jpg",
        quantity: 1,
    },
];